knock_add script now supports many option flags to make it more versatile
knock_add matches knockd.conf and expects iptables at /usr/sbin/iptables

knockd.conf file has been updated to point to knock_add with new arguments

diff --git a/src/utils/knock_add b/src/utils/knock_add
--- a/src/utils/knock_add
+++ b/src/utils/knock_add
@@ -4,35 +4,37 @@ SCRIPT_NAME=$(basename $0)
 
 AWK="/bin/awk"
 GREP="/bin/grep"
-IPTABLES="/sbin/iptables"
+IPTABLES="/usr/sbin/iptables"
 SORT="/bin/sort"
+
+DEFAULT_COMMENT="Added by knockd - ssh"
 
 ADD_CHAIN="INPUT"
 ADD_COMMENT=""
-ADD_METHOD="-I"
+ADD_IP=""
+ADD_METHOD="insert"
 ADD_PORT="22"
 ADD_PROTOCOL="tcp"
 
-COMMENT=0
-DEFAULT_COMMENT="Added by knockd - ssh"
 DRY_RUN=0
 SEEN=0
 VERBOSE=0
 
 usage() {
-	echo "usage: $SCRIPT_NAME [-d|-h|-v] IPADDR"
+	echo "usage: $SCRIPT_NAME [OPTIONS] -a IPADDR"
 	echo "Options:"
+	echo "-a|--address     The IP address to add"
 	echo "-c|--chain       The NetFilter chain to add this address to"
 	echo "-d|--dry-run     Don't actually add IPADDR to $ADD_CHAIN chain"
 	echo "-h|--help        Print this informational screen and exit"
 	echo "-i|--insert      The method to use when adding the rule to NetFilter; valid values are: append, insert"
-	echo "-m|--comment     If present with argument will use that as a comment, if no arg use a boilerplate comment"
+	echo "-m|--comment     If present with optional argument will use that as a comment, if no argument use a boilerplate comment"
 	echo "-p|--port        The port to add allow for default: $ADD_PORT"
 	echo "-t|--protocol    The protocol to add allow for (i.e. tcp, udp) default: $ADD_PROTOCOL"
 	echo "-v|--verbose     Print verbose information about actions"
 }
 
-ARGS=$(getopt -o c:dhv -l "comment:,dry-run,help,verbose" -n $SCRIPT_NAME -- "$@")
+ARGS=$(getopt -o a:c:dhi:m::p:t:v -l "address:,chain:,comment::,dry-run,help,insert:,port:,protocol:,verbose" -n $SCRIPT_NAME -- "$@")
 
 if [ $? -ne 0 ];
 then
@@ -45,17 +47,15 @@ eval set -- "$ARGS"
 
 while true; do
         case "$1" in
-		-c|--comment)
-			shift;
-			COMMENT=1
-			if [ -n "$1" ]; then
-				ADD_COMENT=$1
-				shift;
-			else
-				ADD_COMMENT=$DEFAULT_COMMENT
-			fi
+		-a|--address)
+			ADD_IP=$2
+			shift 2;
 		;;
-                -d|--dry-run)
+		-c|--chain)
+			ADD_CHAIN=$2
+			shift 2;
+		;;
+		-d|--dry-run)
 			DRY_RUN=1
                         shift;
                 ;;
@@ -63,6 +63,28 @@ while true; do
 			usage
 			shift;
 			exit
+		;;
+		-i|--insert)
+			ADD_METHOD=$2
+			shift 2;
+		;;
+		-m|--comment)
+			case "$2" in
+				"")
+					ADD_COMMENT=$DEFAULT_COMMENT;
+					shift 2;;
+				*)
+					ADD_COMMENT=$2;
+					shift 2 ;;
+			esac
+		;;
+		-p|--port)
+			ADD_PORT=$2
+			shift 2;
+		;;
+		-t|--protocol)
+			ADD_PROTOCOL=$2
+			shift 2;
 		;;
 		-v|--verbose)
 			VERBOSE=1
@@ -75,12 +97,52 @@ while true; do
         esac
 done
 
-ADD_IP=$1
+#if [ -z "$1" ]; then
+#	echo "error: ip address required"
+#	usage
+#	exit 1
+#fi
+#
+#ADD_IP=$1
+
+if [ -z "$ADD_IP" ]; then
+	echo "error: ip address required"
+	usage
+	exit 1
+fi
 
 if [ "$VERBOSE" -eq 1 ]; then
 	echo "Testing $ADD_IP"
 fi
 
+# Sanity checking options
+case "$ADD_METHOD" in
+	insert)
+		ADD_METHOD="-I"
+	;;
+	append)
+		ADD_METHOD="-A"
+	;;
+	*)
+		echo "error: Invalid insert value"
+		usage
+		exit 1
+	;;
+esac
+
+COMMENT=""
+if [ -n "$ADD_COMMENT" ]; then
+	COMMENT="-m comment --comment '$ADD_COMMENT'"
+fi
+
+$IPTABLES -L $ADD_CHAIN &> /dev/null
+if [ 0 -ne "$?" ]; then
+	echo "error: $ADD_CHAIN is not a valid NetFilter chain"
+	exit
+fi
+# End Sanity Checks
+
+# Dupe checking
 for IP in `$IPTABLES -n -L KNOCKD | $GREP ACCEPT | $AWK '{print $4}' | $SORT -u`;
 do
 	if [ "$VERBOSE" -eq 1 ]; then
@@ -96,13 +158,14 @@ if [ "$VERBOSE" -eq 1 ]; then
 	echo "SEEN: $SEEN"
 fi
 
+
 if [ "$SEEN" -eq 0 ]; then
 	if [ "$VERBOSE" -eq 1 ]; then
 		echo "Adding $ADD_IP"
-		echo $IPTABLES $ADD_METHOD $ADD_CHAIN -s $ADD_IP -p $ADD_PROTOCOL --dport $ADD_PORT -j ACCEPT
+		echo $IPTABLES $ADD_METHOD $ADD_CHAIN -s $ADD_IP -p $ADD_PROTOCOL --dport $ADD_PORT -j ACCEPT $COMMENT
 	fi
 
 	if [ "$DRY_RUN" -eq 0 ]; then
-		$IPTABLES $ADD_METHOD $ADD_CHAIN -s $ADD_IP -p $ADD_PROTOCOL --dport $ADD_PORT -j ACCEPT
+		eval $IPTABLES $ADD_METHOD $ADD_CHAIN -s $ADD_IP -p $ADD_PROTOCOL --dport $ADD_PORT -j ACCEPT $COMMENT
 	fi
 fi
